### ISSUE TITLE
Support latest  langchain-experimental version

### ISSUE THREAD

**Issue by vincelwt** [ShoggothAI/motleycrew#56]
Hi,
It seems adding motleycrew via Poetry fails with the latest langchain versions:

```bash
> poetry add motleycrew            
Using version ^0.1.5 for motleycrew

Updating dependencies
Resolving dependencies... (0.0s)

Because no versions of motleycrew match >0.1.5,<0.2.0
 and motleycrew (0.1.5) depends on langchain-experimental (>=0.0.57,<0.0.58), motleycrew (>=0.1.5,<0.2.0) requires langchain-experimental (>=0.0.57,<0.0.58).
So, because test-motleycrew depends on both langchain-experimental (^0.0.62) and motleycrew (^0.1.5), version solving failed.
```

These are my Poetry deps:
```
[tool.poetry.dependencies]
python = ">=3.10,<=3.13"
lunary = "^1.0.36"
langchain-core = "^0.2.10"
langchain-openai = "^0.1.10"
langchain-experimental = "^0.0.62"
```

**Comment by whimo** [comment]
Hi @vincelwt, sorry for making you wait.
We wanted to update our Langchain dependency a while ago, but didn't because CrewAI, whom we are optionally dependent on, required Langchain < 0.2. Yesterday their dependency was updated, so I'm hoping to update ours today. Stay tuned!

**Comment by whimo** [comment]
Unfortunately, CrewAI rolled back its update and returned to Langchain 0.1. We can't make the update now as we're using CrewAI agents in our examples and tests.

I'm leaving this issue open and will return to it when CrewAI sorts out its dependencies. Meanwhile, we'll be thinking of a good way to manage optional deps, such as other agent frameworks, so that we can avoid having issues like this one.

**Comment by whimo** [comment]
Merged in https://github.com/ShoggothAI/motleycrew/pull/58

**Comment by whimo** [comment]
https://github.com/ShoggothAI/motleycrew/releases/tag/v0.1.9
